In [2]:
import numpy as np
import pandas as pd
import json
with open('data/test.json',encoding="utf-8") as f:
    data = json.load(f)#字典{"usres":[]}
df=pd.DataFrame(data["users"]) #[{},{}]数组,去掉users
display(df)

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

##### 1.缺失值NAN的处理 (np.nan,None,pd.NA)
###### np.nan:无限数或1/0这种错误(无法显示)
###### None:值为空，给它赋值为None，可以显示出来，但是不方便计算
###### pd.NA:没有填值也不赋值<NA>

In [9]:
df1=pd.DataFrame(
    {
        "a":[1,2,3],
        "b":["a","b",None],
        "c":[np.nan,"c",pd.NA]
    }
)
display(df1)

#查看是否缺失值 df.isna() or df.isnull()

print(df1.isna())#df1.isnull()也可以
print()
print(df1.isna().sum())#统计缺失值:每一列缺失值的个数
print(df1.isna().sum(axis=1)) #统计缺失值:每一行缺失值的个数

   a    b    c
0  1    a  NaN
1  2    b    c
2  3  NaN  NaN

       a      b      c
0  False  False   True
1  False  False  False
2  False   True   True

a    0
b    1
c    2
dtype: int64
0    1
1    0
2    2
dtype: int64

In [13]:
#剔除缺失值df.dropna()

#1.  df1.dropna() #默认剔除所有缺失值所在的行
df1.dropna(how="all") #how="all"某一行所有值都缺失时，剔除该行
#2.  df1.dropna(thresh=2) #某行至少有2个值不缺失时，保留该行

#3.df1.dropna(axis=1,how="all") #某一列所有值都缺失时，剔除该列
#4.df1.dropna(subset=["a"]) #剔除列"a"中缺失值的行

   a    b    c
0  1    a  NaN
1  2    b    c
2  3  NaN  NaN

##### 2.填充缺失值
###### fillna:填充缺失值
###### replace:替换缺失值
##### fillna不会原地修改数据，需要赋值

In [37]:
#weather中有缺失值
weather=pd.read_csv("data/weather_withna.csv")
display(weather)
print(weather.isna().sum(axis=0)) #axes=0表示按列统计缺失值个数

#填充缺失值 fillna()
weather=weather.fillna({"precipitation":20,'temp_max':10})
display(weather) #字典形式填充

wind_mean=weather["wind"].mean()
print(wind_mean)
weather=weather.fillna({"wind":round(wind_mean,3)})
display(weather) #填充平均值

#用周边值填充 df.ffill() :ffill(forward fill)向前填充
weather=weather.ffill()
display(weather)

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            NaN       NaN       NaN   NaN      NaN
1457  2015-12-28            NaN       NaN       NaN   NaN      NaN
1458  2015-12-29            NaN       NaN       NaN   NaN      NaN
1459  2015-12-30            NaN       NaN       NaN   NaN      NaN
1460  2015-12-31           20.6      12.2       5.0   3.8     rain

[1461 rows x 6 columns]

date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27           20.0      10.0       NaN   NaN      NaN
1457  2015-12-28           20.0      10.0       NaN   NaN      NaN
1458  2015-12-29           20.0      10.0       NaN   NaN      NaN
1459  2015-12-30           20.0      10.0       NaN   NaN      NaN
1460  2015-12-31           20.6      12.2       5.0   3.8     rain

[1461 rows x 6 columns]

3.2420552677029364

            date  precipitation  temp_max  temp_min   wind  weather
0     2012-01-01            0.0      12.8       5.0  4.700  drizzle
1     2012-01-02           10.9      10.6       2.8  4.500     rain
2     2012-01-03            0.8      11.7       7.2  2.300     rain
3     2012-01-04           20.3      12.2       5.6  4.700     rain
4     2012-01-05            1.3       8.9       2.8  6.100     rain
...          ...            ...       ...       ...    ...      ...
1456  2015-12-27           20.0      10.0       NaN  3.242      NaN
1457  2015-12-28           20.0      10.0       NaN  3.242      NaN
1458  2015-12-29           20.0      10.0       NaN  3.242      NaN
1459  2015-12-30           20.0      10.0       NaN  3.242      NaN
1460  2015-12-31           20.6      12.2       5.0  3.800     rain

[1461 rows x 6 columns]

            date  precipitation  temp_max  temp_min   wind  weather
0     2012-01-01            0.0      12.8       5.0  4.700  drizzle
1     2012-01-02           10.9      10.6       2.8  4.500     rain
2     2012-01-03            0.8      11.7       7.2  2.300     rain
3     2012-01-04           20.3      12.2       5.6  4.700     rain
4     2012-01-05            1.3       8.9       2.8  6.100     rain
...          ...            ...       ...       ...    ...      ...
1456  2015-12-27           20.0      10.0       4.4  3.242      sun
1457  2015-12-28           20.0      10.0       4.4  3.242      sun
1458  2015-12-29           20.0      10.0       4.4  3.242      sun
1459  2015-12-30           20.0      10.0       4.4  3.242      sun
1460  2015-12-31           20.6      12.2       5.0  3.800     rain

[1461 rows x 6 columns]

#### 数据类型替换

In [52]:
data={
    "name":["Alice","Alice","Bob","Tom","Bob","Alice"],
    "age":[20,20,22,20,21,25],
    "sex":["male","male","male","male","female","male"]
}
df=pd.DataFrame(data,columns=["name","age","sex"])
display(df)

#检测重复行 .duplicated()
print(df.duplicated()) #某行数据完全相同，返回True
display(df.drop_duplicates()) #剔除重复行:默认剔除完全相同的行

display(df.drop_duplicates(subset=["name"])) #剔除重复行:根据某一列剔除:剔除name列重复的行
#df.drop_duplicates(subset=["name"],keep="last") #保留最后一次出现的行

    name  age     sex
0  Alice   20    male
1  Alice   20    male
2    Bob   22    male
3    Tom   20    male
4    Bob   21  female
5  Alice   25    male

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

    name  age     sex
0  Alice   20    male
2    Bob   22    male
3    Tom   20    male
4    Bob   21  female
5  Alice   25    male

    name  age   sex
0  Alice   20  male
2    Bob   22  male
3    Tom   20  male

In [60]:
#数据类型转换   列.astype(数据类型)
df=pd.read_csv("data/sleep.csv")
display(df)
print(df.dtypes)
#age的类型是int64,转换成小一点的数据类型int16。不占用太多内存

df["age"]=df["age"].astype(np.int16) #列的类型转换后赋值给列 原地修改数据
#display(df["age"].astype(np.int16)) #不原地修改数据,返回新的df表格，不推荐使用

#字符串处理比较慢，原来的genger为str类型，如：在比较str=="male"时太慢，转换成catagory类别型数据后比较快
df["gender"]=df["gender"].astype("category") #转换成类别型数据 catagory中有male,female
display(df)
print(df["age"].dtypes)
print(df["gender"].dtypes)

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

int16
category

#### 数据变形()

In [13]:
#pd.melt():数据变形,将宽表转为长表
#id_vars:不变列,value_vars:变列.value_name:变列的名字,var_name:取值列的名字
df=pd.DataFrame(
    {
        "name":["Alice","Bob"],
        "age":[20,21],
        "math":[90,80],
        "english":[80,90],
        "chinese":[80,90]
    },index=["A","B"]
)
display(df)
#不是原地修改数据，返回新的df表格
df1=pd.melt(df,id_vars=["name","age"],value_vars=["math","english","chinese"],value_name="score",var_name="subject")
df1.sort_values("name",inplace=True) #原地修改数据，不返回新的df表格，按照名字排序
display(df1)

    name  age  math  english  chinese
A  Alice   20    90       80       80
B    Bob   21    80       90       90

    name  age  subject  score
0  Alice   20     math     90
2  Alice   20  english     80
4  Alice   20  chinese     80
1    Bob   21     math     80
3    Bob   21  english     90
5    Bob   21  chinese     90

In [32]:
#分列 sleep.csv中有血压值，想要分开最高和最低血压值
sleep=pd.read_csv("data/sleep.csv")
sleep_part=sleep.head(10)
display(sleep_part)
print(sleep_part.dtypes["blood_pressure"]) #血压值124/70是字符串类型

#把高低血压分开，变成两列
#列.str:指对字符串处理(血压是str)   .split("/",expand=True):分割字符串，“/“是分隔符表示先分割成124,70, expand=True：变成两列
splt=sleep_part["blood_pressure"].str.split("/",expand=True) #分割字符串

sleep_part[["Maxblood_pressure","Minblood_pressure"]]=splt #赋值给两列 注意加两层[[]]

#类型转换,str转int16
sleep_part["Maxblood_pressure"]=sleep_part["Maxblood_pressure"].astype(np.int16)
sleep_part["Minblood_pressure"]=sleep_part["Minblood_pressure"].astype(np.int16)
print(sleep_part["Maxblood_pressure"].dtypes)
display(sleep_part)

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
5,6,Female,47,Student,6.1,6.9,24,4,Normal,123/60,87,9485,NaN
6,7,Male,22,Office Worker,5.1,6.1,26,6,Obese,121/70,66,15680,NaN
7,8,Male,49,Office Worker,10.7,6.2,49,8,Obese,134/87,59,18767,NaN
8,9,Male,25,Manual Labor,11.9,7.2,27,8,Underweight,112/63,99,16397,Sleep Apnea
9,10,Female,51,Retired,8.2,4.0,64,5,Overweight,125/84,76,12744,NaN

str
int16

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,Maxblood_pressure,Minblood_pressure
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN,124,70
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN,131,86
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN,122,70
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN,124,72
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia,133,78
5,6,Female,47,Student,6.1,6.9,24,4,Normal,123/60,87,9485,NaN,123,60
6,7,Male,22,Office Worker,5.1,6.1,26,6,Obese,121/70,66,15680,NaN,121,70
7,8,Male,49,Office Worker,10.7,6.2,49,8,Obese,134/87,59,18767,NaN,134,87
8,9,Male,25,Manual Labor,11.9,7.2,27,8,Underweight,112/63,99,16397,Sleep Apnea,112,63
9,10,Female,51,Retired,8.2,4.0,64,5,Overweight,125/84,76,12744,NaN,125,84

##### 数据分箱：将连续数据分割成一个个区间  pd.cut(pd,bins,labels)
###### pd:数据列  bins:区间个数或区间范围列表 labels:每个区间的标签(名字)

In [47]:
df=pd.read_csv("data/employees.csv")
df1=df.head(10)[["employee_id","salary"]]
display(df1)

#将薪资划分成2个区间，看每行的薪资落在哪个区间
#bins=整数2:    分成两个区间;  把salary.min~salary.max:薪资范围分成两个区间:4180-14100-2400
print(pd.cut(df1["salary"],bins=2))
print()
count=pd.cut(df1["salary"],bins=2).value_counts() #统计每个区间的人数
print(count)

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

0    (14100.0, 24000.0]
1    (14100.0, 24000.0]
2    (14100.0, 24000.0]
3     (4180.2, 14100.0]
4     (4180.2, 14100.0]
5     (4180.2, 14100.0]
6     (4180.2, 14100.0]
7     (4180.2, 14100.0]
8     (4180.2, 14100.0]
9     (4180.2, 14100.0]
Name: salary, dtype: category
Categories (2, interval[float64, right]): [(4180.2, 14100.0] < (14100.0, 24000.0]]

salary
(4180.2, 14100.0]     7
(14100.0, 24000.0]    3
Name: count, dtype: int64

In [51]:
#用法2:bins=自定义区间列表 labels=区间名字
print(pd.cut(df1["salary"],bins=[0,10000,20000,30000],labels=["低","中","高"]))
df1["收入范围"]=pd.cut(df1["salary"],bins=[0,10000,20000,30000],labels=["低","中","高"])
display(df1)

0    高
1    中
2    中
3    低
4    低
5    低
6    低
7    低
8    中
9    低
Name: salary, dtype: category
Categories (3, str): ['低' < '中' < '高']

   employee_id   salary 收入范围
0          100  24000.0    高
1          101  17000.0    中
2          102  17000.0    中
3          103   9000.0    低
4          104   6000.0    低
5          105   4800.0    低
6          106   4800.0    低
7          107   4200.0    低
8          108  12000.0    中
9          109   9000.0    低

##### pd.qcut(pd,q,labels):将数据分成几个等频区间(每个区间里的人数差不多)

In [54]:
print(pd.qcut(df1["salary"],q=3,labels=["低","中","高"]))
#统计每个区间的人数,可以发现每个区间的人数差不多    等频区间
print(pd.qcut(df1["salary"],q=3,labels=["低","中","高"]).value_counts())

0    高
1    高
2    高
3    中
4    低
5    低
6    低
7    低
8    中
9    中
Name: salary, dtype: category
Categories (3, str): ['低' < '中' < '高']
salary
低    4
中    3
高    3
Name: count, dtype: int64

In [61]:
#使用sleep.csv数据，将睡眠时长分成3个区间
df=pd.read_csv("data/sleep.csv")
df1=df.head(10)[["person_id","sleep_quality"]] #取前10行,只取id和total_sleep两列
display(df1)

#数值——>分箱实现类别——>统计
df1["睡眠质量"]=pd.cut(df1["sleep_quality"],bins=3,labels=["低","中","高"])
display(df1)
print(df1["睡眠质量"].value_counts())
print()

#.astype("category")转换成类别型数据,并统计的方法   字符串——>类别——>统计     对数值操作需要分箱转化为类别再统计
df["gender"]=df["gender"].astype("category") #转换成分类型数据 catagory:{"male","female"}
count=df["gender"].value_counts()
print(count)
print()

#都是catagory类型数据
print(df["gender"])
print(df1["睡眠质量"])

   person_id  sleep_quality
0          1            7.0
1          2            4.9
2          3            6.0
3          4           10.0
4          5            9.5
5          6            6.9
6          7            6.1
7          8            6.2
8          9            7.2
9         10            4.0

   person_id  sleep_quality 睡眠质量
0          1            7.0    中
1          2            4.9    低
2          3            6.0    低
3          4           10.0    高
4          5            9.5    高
5          6            6.9    中
6          7            6.1    中
7          8            6.2    中
8          9            7.2    中
9         10            4.0    低

睡眠质量
中    5
低    3
高    2
Name: count, dtype: int64

gender
Female    201
Male      199
Name: count, dtype: int64
0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']
0    中
1    低
2    低
3    高
4    高
5    中
6    中
7    中
8    中
9    低
Name: 睡眠质量, dtype: category
Categories (3, str): ['低' < '中' < '高']

In [ ]:
#df.set_index("name",inplace=True):设置索引
#df.reset_index(inplace=True,inplace=True):重置索引 把之前设置的索引删除
#df.renaem(columns={"name":"姓名"},index={0:4}):列名或索引重命名

#下面的属性是要全改，如果要部分改，用上面的方法
#df.index=[1,2,3,4]:重置索引
#df.coluums=["a","b"]:重置列名