In [1]:
import numpy as np
import pandas as pd
import json

#### 时间数据的处理
##### pd.Timestamp("2026-09-22 17:24)   (时间戳)时刻

In [21]:
time=pd.Timestamp("2026-09-22 17:24")
print(time)
print(type(time))

#属性
print(time.year)
print(time.month)
print(time.day)
print(time.hour)
print(time.minute)
print(time.second)
print(time.quarter)
print()

#方法
print("是否是月底",time.is_month_end)
print("星期",time.day_name())
print("转化为天",time.to_period("D")) #转化为天,月M,年Y,周W,小时H,分钟T,秒S
print("转化为月",time.to_period("M")) #转化为月

2026-09-22 17:24:00
<class 'pandas.Timestamp'>
2026
9
22
17
24
0
3

是否是月底 False
星期 Tuesday
转化为天 2026-09-22
转化为月 2026-09

In [34]:
#字符串转换成时间戳类型(我们导入来的数据里的时间多是字符串类型)
time_str="2026-09-22 17:24"
print(pd.to_datetime(time_str))
print(type(pd.to_datetime(time_str)))
print()

#DataFame中的例子
df=pd.DataFrame(
    {
    "name":["Alice","Bob"],
    "生日":["1990-03-15","1988-05-20"]
}
)
print(df["生日"].dtype)
#将字符串转化为时间戳类型
df["生日"]=pd.to_datetime(df["生日"])
print(df["生日"].dtype)
print()

print(df["生日"].dt.year) #直接df["生日"].year会出错       df["生日"]是Series类型    里面的属性才是时间戳类型  dt:datetime
#单个时间戳才直接.year  对于属性为时间戳的Series要用.dt 把Series里面的时间戳类型提取出来

df["weekday"]=df["生日"].dt.day_name()
df["year"]=df["生日"].dt.year
display(df)

2026-09-22 17:24:00
<class 'pandas.Timestamp'>

str
datetime64[us]

0    1990
1    1988
Name: 生日, dtype: int32

    name         生日   weekday  year
0  Alice 1990-03-15  Thursday  1990
1    Bob 1988-05-20    Friday  1988

In [42]:
#读入一个csv文件
df=pd.read_csv("data/weather.csv")
df_head=df.head(10)
display(df_head)
print(df_head["date"].dtype)#字符串类型

df_head["datetime"]=pd.to_datetime(df_head["date"])#把"date"转化为时间戳类型，并存入"datetime"列
display(df_head)
print(df_head["datetime"].dtype) #datetime64[us]

df_head["weekday"]=df_head["datetime"].dt.weekday
display(df_head)

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain
5  2012-01-06            2.5       4.4       2.2   2.2     rain
6  2012-01-07            0.0       7.2       2.8   2.3     rain
7  2012-01-08            0.0      10.0       2.8   2.0      sun
8  2012-01-09            4.3       9.4       5.0   3.4     rain
9  2012-01-10            1.0       6.1       0.6   3.4     rain

str

         date  precipitation  temp_max  temp_min  wind  weather   datetime
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle 2012-01-01
1  2012-01-02           10.9      10.6       2.8   4.5     rain 2012-01-02
2  2012-01-03            0.8      11.7       7.2   2.3     rain 2012-01-03
3  2012-01-04           20.3      12.2       5.6   4.7     rain 2012-01-04
4  2012-01-05            1.3       8.9       2.8   6.1     rain 2012-01-05
5  2012-01-06            2.5       4.4       2.2   2.2     rain 2012-01-06
6  2012-01-07            0.0       7.2       2.8   2.3     rain 2012-01-07
7  2012-01-08            0.0      10.0       2.8   2.0      sun 2012-01-08
8  2012-01-09            4.3       9.4       5.0   3.4     rain 2012-01-09
9  2012-01-10            1.0       6.1       0.6   3.4     rain 2012-01-10

datetime64[us]

,date,precipitation,temp_max,temp_min,wind,weather,datetime,weekday
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle,2012-01-01,6
1,2012-01-02,10.9,10.6,2.8,4.5,rain,2012-01-02,0
2,2012-01-03,0.8,11.7,7.2,2.3,rain,2012-01-03,1
3,2012-01-04,20.3,12.2,5.6,4.7,rain,2012-01-04,2
4,2012-01-05,1.3,8.9,2.8,6.1,rain,2012-01-05,3
5,2012-01-06,2.5,4.4,2.2,2.2,rain,2012-01-06,4
6,2012-01-07,0.0,7.2,2.8,2.3,rain,2012-01-07,5
7,2012-01-08,0.0,10.0,2.8,2.0,sun,2012-01-08,6
8,2012-01-09,4.3,9.4,5.0,3.4,rain,2012-01-09,0
9,2012-01-10,1.0,6.1,0.6,3.4,rain,2012-01-10,1

In [44]:
#简化时间戳类型转换 parse:解析的英文  parse_dates:解析为日期型
df=pd.read_csv("data/weather.csv",parse_dates=["date"]) #parse_dates=["date"] 自动将"date"转化为时间戳类型
print(df["date"].dtype) #datetime64[ns]类型

datetime64[us]

In [50]:
#日期作为索引：把之前index换成date  weather.csv中用date代替索引可展示每天时间，便于观察
#df.set_index("date",inplace=True)
#display(df.head(10))

#注意：执行完一次后就已经完成，如果再次执行会报错，需要重新导入未修改的数据
display(df.head(10).loc["2012-01-01":"2012-01-05"])

            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05            1.3       8.9       2.8   6.1     rain

In [9]:
#时间间隔
time1=pd.Timestamp("2026-09-22 17:24")
time2=pd.Timestamp("2026-09-23 18:24")
time3=time2-time1
print(time3)

df=pd.read_csv("data/weather.csv",parse_dates=["date"])
#计算时间间隔
df["delta"]=df["date"]-df["date"][0]
#将时间间隔设置为索引，便于观察
df.set_index("delta",inplace=True)
display(df.head(10))
#按照索引查找
print(df.loc["5 days" :"10 days"])

1 days 01:00:00

             date  precipitation  temp_max  temp_min  wind  weather
delta
0 days 2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 days 2012-01-02           10.9      10.6       2.8   4.5     rain
2 days 2012-01-03            0.8      11.7       7.2   2.3     rain
3 days 2012-01-04           20.3      12.2       5.6   4.7     rain
4 days 2012-01-05            1.3       8.9       2.8   6.1     rain
5 days 2012-01-06            2.5       4.4       2.2   2.2     rain
6 days 2012-01-07            0.0       7.2       2.8   2.3     rain
7 days 2012-01-08            0.0      10.0       2.8   2.0      sun
8 days 2012-01-09            4.3       9.4       5.0   3.4     rain
9 days 2012-01-10            1.0       6.1       0.6   3.4     rain

              date  precipitation  temp_max  temp_min  wind weather
delta
5 days  2012-01-06            2.5       4.4       2.2   2.2    rain
6 days  2012-01-07            0.0       7.2       2.8   2.3    rain
7 days  2012-01-08            0.0      10.0       2.8   2.0     sun
8 days  2012-01-09            4.3       9.4       5.0   3.4    rain
9 days  2012-01-10            1.0       6.1       0.6   3.4    rain
10 days 2012-01-11            0.0       6.1      -1.1   5.1     sun

In [13]:
days=pd.date_range("2012-01-01","2012-01-05",freq='D') #生成一个时间序列,每天一个时间戳
print(days)
print()
days2=pd.date_range("2012-01-01",periods=10,freq='W') #每周一个时间戳，总共10个
print(days2)

DatetimeIndex(['2012-01-01', '2012-01-02', '2012-01-03', '2012-01-04',
               '2012-01-05'],
              dtype='datetime64[us]', freq='D')

DatetimeIndex(['2012-01-01', '2012-01-08', '2012-01-15', '2012-01-22',
               '2012-01-29', '2012-02-05', '2012-02-12', '2012-02-19',
               '2012-02-26', '2012-03-04'],
              dtype='datetime64[us]', freq='W-SUN')

In [15]:
#重采样 按照年份汇总，相同年份的数据汇总到一起
df=pd.read_csv("data/weather.csv",parse_dates=["date"])
df.set_index("date",inplace=True)
display(df)

#得到每年的最高与最低温度的平均值  YE:年末 YS:年初   比后面学的的group by更便捷
year_temp=df[["temp_max","temp_min"]].resample("YE").mean()
display(year_temp)

            precipitation  temp_max  temp_min  wind  weather
date
2012-01-01            0.0      12.8       5.0   4.7  drizzle
2012-01-02           10.9      10.6       2.8   4.5     rain
2012-01-03            0.8      11.7       7.2   2.3     rain
2012-01-04           20.3      12.2       5.6   4.7     rain
2012-01-05            1.3       8.9       2.8   6.1     rain
...                   ...       ...       ...   ...      ...
2015-12-27            8.6       4.4       1.7   2.9     rain
2015-12-28            1.5       5.0       1.7   1.3     rain
2015-12-29            0.0       7.2       0.6   2.6      fog
2015-12-30            0.0       5.6      -1.0   3.4      sun
2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

#### 分组聚合:   group by("分组字段")["聚合字段"].聚合函数()

In [32]:
df=pd.read_csv("data/employees.csv")

#先进行数据清洗

#id有缺失值，将缺失值先处理，才能对ID进行类型转换和分组 (缺失值处理：填充，删除)
print(df["department_id"].isna().sum())
#只有一行缺失值，直接删除该行就行 (inplace=True 直接在原数据上修改)
df.dropna(subset=["department_id"],inplace=True) #只检查department_id列是否有缺失值，若有则删除该行
#将department_id由浮点型转化为整型
df["department_id"]=df["department_id"].astype("int16")
display(df)

#按照部门ID分组，计算每个部门的员工数量和平均薪资 group by
#("ID")["薪资"].count()  :按照ID分组，对[薪资]计数  .count()是聚合函数
count=df.groupby("department_id")["employee_id"].count()
mean=df.groupby("department_id")[["salary"]].mean()
#[[]]表示返回的时DataFrame类型  只[]表示返回的是Series类型
display(count.to_frame())
print()

#处理mean中salay的小数点后两位
mean["salary"]=round(mean["salary"],2)
mean.reset_index(inplace=True)#重置索引，便于观察
mean.sort_values("salary",ascending=False,inplace=True) #按照salary降序排列,inplace=True 直接在原数据上修改
display(mean)

1

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110

               employee_id
department_id
10                       1
20                       2
30                       6
40                       1
50                      45
60                       5
70                       1
80                      34
90                       3
100                      6
110                      2

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [40]:
#多条件分组：根据不同部门(department_id)，不同岗位(job_id)的平均薪资
mean=df.groupby(["department_id","job_id"])[["salary"]].mean() #[[salay]]:返回DataFrame类型
mean=mean.reset_index()
mean["salary"]=round(mean["salary"],2)
mean.sort_values("salary",ascending=False,inplace=True)
display(mean)

    department_id      job_id    salary
13             90     AD_PRES  24000.00
14             90       AD_VP  17000.00
1              20      MK_MAN  13000.00
11             80      SA_MAN  12200.00
16            100      FI_MGR  12000.00
18            110      AC_MGR  12000.00
4              30      PU_MAN  11000.00
10             70      PR_REP  10000.00
12             80      SA_REP   8396.55
17            110  AC_ACCOUNT   8300.00
15            100  FI_ACCOUNT   7920.00
8              50      ST_MAN   7280.00
5              40      HR_REP   6500.00
2              20      MK_REP   6000.00
9              60     IT_PROG   5760.00
0              10     AD_ASST   4400.00
6              50    SH_CLERK   3215.00
7              50    ST_CLERK   2785.00
3              30    PU_CLERK   2780.00