#### 企鹅案例
##### 1.导入库
##### 2.导入数据
##### 3.数据清洗
##### 4.数据特征的构造（拆开某列成两列，新加一些列和数据,转换类型等等）
##### 5.数据分析
##### 6.数据可视化

##### 分组聚合（按多个字段分组的单个聚合：实现单列的单个统计函数）:   group by(["分组字段1","分组字段2"])["聚合字段"].聚合函数()
##### 分组聚合（按多个字段分组的的多个聚合：实现多列的多个统计函数）:   group by(["分组字段1","分组字段2"]).agg({"聚合字段1":["统计  1","统计2"],...,"聚合字段2":["统计1","统计2"]})

In [14]:
#1.导入库
import pandas as pd
import numpy as np

#2.导入数据
penguins=pd.read_csv('data/penguins.csv')
#检查部分数据以及其类型
display(penguins.head(10))
print(penguins.info())
print()

#3.数据清洗
#检查缺失值
print(penguins.isna().sum())
print()
#发现缺失值较少，直接原地删除
penguins.dropna(inplace=True)
print(penguins.isna().sum()) #缺失值都无了
print()

#4.数据特征的构造
#把sex转化成"category"分类类型
penguins["sex"]=penguins["sex"].astype("category")
print(penguins["sex"])
#添加一列长宽比
penguins["bill_ratio"]=round(penguins["bill_length_mm"]/penguins["bill_depth_mm"],2)
display(penguins.head(10))
print()

#5.数据分析
#把体重分为低中高3个等级 pd.cut(列，bins=n,labels=[分级名称列表])
labels=["low","medium","high"]
penguins["weight_level"]=pd.cut(penguins["body_mass_g"],bins=3,labels=labels)
display(penguins.head(10))
print()
#计算个等级的个数  列.value_counts():计算每个值的个数
print(penguins["weight_level"].value_counts())

#按照性别分组分析  统计的特别多时用 agg({"统计1"，"统计2"，"统计3"，...})合并起来 [sex]的【】可以不写，一个的分组字段
sex_group=penguins.groupby("sex").agg({
    "body_mass_g":["count","mean"] #统计企鹅个数和体重平均值
})
display(sex_group)
print()

#按照岛屿分组分析
island_group=penguins.groupby(["island"]).agg({
    "body_mass_g":["count","mean"], #统计企鹅个数和体重平均值
    "bill_ratio":["min","max"]  #计算长宽比的最小最大值
})
display(island_group)
print()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 24.9 KB
None

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

0        Male
1      Female
2      Female
4      Female
5        Male
        ...
338    Female
340    Female
341      Male
342    Female
343      Male
Name: sex, Length: 333, dtype: category
Categories (2, str): ['Female', 'Male']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.09
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.27
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.24
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.90
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.91
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female,2.19
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male,2.00
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,Female,2.34
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male,1.82
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male,1.64

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio,weight_level
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.09,low
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.27,low
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.24,low
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.90,low
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.91,low
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female,2.19,low
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male,2.00,medium
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,Female,2.34,low
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male,1.82,low
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male,1.64,medium

weight_level
low       150
medium    128
high       55
Name: count, dtype: int64

       body_mass_g
             count         mean
sex
Female         165  3862.272727
Male           168  4545.684524

          body_mass_g              bill_ratio
                count         mean        min   max
island
Biscoe            163  4719.171779       1.87  3.61
Dream             123  3718.902439       1.86  3.26
Torgersen          47  3708.510638       1.64  2.45

#### 睡眠质量案例

In [47]:
#1.导入库
import pandas as pd
import numpy as np

#2.导入数据
sleep_quality=pd.read_csv('data/sleep.csv')
display(sleep_quality.head(10))
print()

#3.数据清洗
#检查缺失值
print(sleep_quality.isna().sum())
print()
#发现sleep_disorder缺失值较多，不可删除,进行填充   fillna(填充值)
sleep_quality.fillna("unknown",inplace=True)
print(sleep_quality.isna().sum()) #缺失值都无了
print()

#4.数据特征的构造
#genger转换为分类类型
sleep_quality["gender"]=sleep_quality["gender"].astype("category")
print(sleep_quality["gender"].dtypes)
print()

#输出职业的个数发现比较少    把职业occupation从str转为category分类类型
print(sleep_quality["occupation"].value_counts())
sleep_quality["occupation"]=sleep_quality["occupation"].astype("category")
print(sleep_quality["occupation"].dtypes)
print()

#血压值分成高低血压 split(列，分割符号) str:把blood_pressure当作字符串处理，然后分割符号为"/"  #expand=True:分割后变成两列
sleep_quality[["high_pressure","low_pressure"]]=sleep_quality["blood_pressure"].str.split("/",expand=True)
display(sleep_quality.head(10))
print()

#把睡眠质量分箱为“差，中，优”   pd.cut(列，bins=n,labels=[分级名称列表])
labels=["poor","medium","excellent"]
sleep_quality["sleep_level"]=pd.cut(sleep_quality["sleep_quality"],bins=3,labels=labels)
#把年龄分箱为“青年，中年，老年”
labels=["youth","middle_age","old"]
sleep_quality["age_level"]=pd.cut(sleep_quality["age"],bins=3,labels=labels)
display(sleep_quality.head(10))
print()

#5.数据分析
#输出BMI各等级的人数
print(sleep_quality["bmi_category"].value_counts())
print()

#根据不同的BMI分组，观察不同BMI人群的睡眠质量分布
#groupby("分组字段")[["聚合字段"]].value_counts()  单个分组字段，单个聚合字段
count=sleep_quality.groupby("bmi_category")["sleep_level"].value_counts()
display(count.to_frame("count"))
print()

#groupby(["分组字段"]).agg({"聚合字段1":["统计函数"],"聚合字段2":["统计函数"]})  多个分组字段，多个聚合字段
#根据年龄和BMI分组，计算不同年龄段不同BMI人群的睡眠时间和压力水平
BY_group=sleep_quality.groupby(["age_level","bmi_category"]).agg({
    "person_id":["count"], #计算人数
    "sleep_duration":["mean"],#计算睡眠时间平均值
    "stress_level":["mean"] #计算压力水平平均值
     })
#保留两位小数  列.round(2)
BY_group[["sleep_duration","stress_level"]]=BY_group[["sleep_duration","stress_level"]].round(2)
#给BY_group的"person_id"重命名
BY_group.rename(columns={"person_id":"person"},inplace=True)
display(BY_group)

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
5,6,Female,47,Student,6.1,6.9,24,4,Normal,123/60,87,9485,NaN
6,7,Male,22,Office Worker,5.1,6.1,26,6,Obese,121/70,66,15680,NaN
7,8,Male,49,Office Worker,10.7,6.2,49,8,Obese,134/87,59,18767,NaN
8,9,Male,25,Manual Labor,11.9,7.2,27,8,Underweight,112/63,99,16397,Sleep Apnea
9,10,Female,51,Retired,8.2,4.0,64,5,Overweight,125/84,76,12744,NaN

person_id                    0
gender                       0
age                          0
occupation                   0
sleep_duration               0
sleep_quality                0
physical_activity_level      0
stress_level                 0
bmi_category                 0
blood_pressure               0
heart_rate                   0
daily_steps                  0
sleep_disorder             290
dtype: int64

person_id                  0
gender                     0
age                        0
occupation                 0
sleep_duration             0
sleep_quality              0
physical_activity_level    0
stress_level               0
bmi_category               0
blood_pressure             0
heart_rate                 0
daily_steps                0
sleep_disorder             0
dtype: int64

category

occupation
Student          110
Office Worker     99
Manual Labor      96
Retired           95
Name: count, dtype: int64
category

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,high_pressure,low_pressure
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,unknown,124,70
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,unknown,131,86
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,unknown,122,70
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,unknown,124,72
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia,133,78
5,6,Female,47,Student,6.1,6.9,24,4,Normal,123/60,87,9485,unknown,123,60
6,7,Male,22,Office Worker,5.1,6.1,26,6,Obese,121/70,66,15680,unknown,121,70
7,8,Male,49,Office Worker,10.7,6.2,49,8,Obese,134/87,59,18767,unknown,134,87
8,9,Male,25,Manual Labor,11.9,7.2,27,8,Underweight,112/63,99,16397,Sleep Apnea,112,63
9,10,Female,51,Retired,8.2,4.0,64,5,Overweight,125/84,76,12744,unknown,125,84

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,high_pressure,low_pressure,sleep_level,age_level
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,unknown,124,70,medium,youth
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,unknown,131,86,medium,middle_age
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,unknown,122,70,medium,middle_age
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,unknown,124,72,excellent,youth
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia,133,78,excellent,old
5,6,Female,47,Student,6.1,6.9,24,4,Normal,123/60,87,9485,unknown,123,60,medium,middle_age
6,7,Male,22,Office Worker,5.1,6.1,26,6,Obese,121/70,66,15680,unknown,121,70,medium,youth
7,8,Male,49,Office Worker,10.7,6.2,49,8,Obese,134/87,59,18767,unknown,134,87,medium,middle_age
8,9,Male,25,Manual Labor,11.9,7.2,27,8,Underweight,112/63,99,16397,Sleep Apnea,112,63,excellent,youth
9,10,Female,51,Retired,8.2,4.0,64,5,Overweight,125/84,76,12744,unknown,125,84,poor,middle_age

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

                          count
bmi_category sleep_level
Normal       medium          52
             excellent       31
             poor             8
Obese        medium          52
             excellent       30
             poor            16
Overweight   medium          52
             excellent       38
             poor            19
Underweight  medium          50
             excellent       30
             poor            22

                        person sleep_duration stress_level
                         count           mean         mean
age_level  bmi_category
youth      Normal           50           8.10         4.86
           Obese            58           8.25         5.53
           Overweight       63           8.21         5.32
           Underweight      61           7.60         5.43
middle_age Normal           36           7.42         4.94
           Obese            36           7.81         5.89
           Overweight       39           8.25         5.97
           Underweight      40           8.50         5.75
old        Normal            5           7.42         4.20
           Obese             4           7.90         8.00
           Overweight        7           8.97         6.71
           Underweight       1          10.50         6.00